apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: ordersystem-ms-products-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordersystem-ms-products-deployment
  template:
    metadata:
      labels:
        app: ordersystem-ms-products-deployment
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: order-system-ms-products-api-container
          image: 853003360406.dkr.ecr.us-east-1.amazonaws.com/order-system-products:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: api-configmap
