apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-svc
  name: svc-ordersystem-ms-payments-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: ordersystem-ms-payments-deployment
