apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: ordersystem-ms-payments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordersystem-ms-payments-deployment
  template:
    metadata:
      labels:
        app: ordersystem-ms-payments-deployment
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: order-system-ms-payments-api-container
          image: 575258201927.dkr.ecr.us-east-1.amazonaws.com/order-system-payments:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: api-configmap
