apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
  labels:
    name: api-configmap
data:
  DATABASE_URL: mysql://msproducts:Fiap24msproducts@dbproducts.c6zg4ekfwyhz.us-east-1.rds.amazonaws.com:3306/dbMySqlPayments
  NODE_LOCAL_PORT: "3001"
  ENDPOINT: https://sqs.us-east-1.amazonaws.com/853003360406/
  QUEUE: sendOrder-consumerProduct-queue
