apiVersion: v1
kind: Service
metadata:
  name: svc-ordersystem-ms-products-nodeport
spec:
  type: NodePort
  selector:
    app: svc-ordersystem-ms-products-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
