version: '3.9'

services:
  mysqldb:
    image: mysql:latest
    container_name: dbMySqlProduct
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    expose:
      - $MYSQLDB_LOCAL_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - orderSystemMsProduct

  api:
    depends_on:
      - mysqldb
    container_name: nestjsProduct
    image: nestjs-product
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
    environment:
      - DATABASE_URL=$DATABASE_URL
      - TOKEN_MERCADO_PAGO=$TOKEN_MERCADO_PAGO
      - USERID=$USERID
      - POSID=$POSID
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - orderSystemMsProduct

  rabbitmq:
    depends_on:
      - api
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - db:/var/lib/rabbitmq
    networks:
      - orderSystemMsProduct

volumes:
  db:
networks:
  orderSystemMsProduct:
    driver: bridge
