# GET
# Busca Produtos
###

GET http://localhost:3001/products/1
Content-Type: application/json

# POST
# Criar Produtos
###

POST http://localhost:3001/products
Content-Type: application/json
user: 2

{
  "name": "sorvete",
  "priceUnit": 4,
  "categoryID": 1,
  "stock": [{
    "quantity": 100,
    "quantityAvailable": 100
  }]
}