# GET
# Busca Produtos
###

GET http://localhost:3001/products/1
Content-Type: application/json
user: 2

# POST
# Criar Produtos
###

POST http://localhost:3001/products
Content-Type: application/json
user: 2

{
  "name": "sorvete Chocolate",
  "priceUnit": 3,
  "categoryID": 1
}

# PATCH
# Atualizar Produtos
###

PATCH http://localhost:3001/products
Content-Type: application/json
user: 2

{
  "id": 1,
  "name": "sorvete",
  "priceUnit": 5,
  "categoryID": 1
}