# GET
# Busca Produtos
###

GET http://localhost:3001/stock/1
Content-Type: application/json
user: 2

# POST
# Criar Produtos
###

POST http://localhost:3001/stock
Content-Type: application/json
user: 2

{
  "quantity": 100,
  "quantityAvailable": 100,
  "productID": 1
}