# GET
# Busca categoria
###

GET http://localhost:3001/categories/1
Content-Type: application/json
user: 2

# POST
# Criar categoria
###

POST http://localhost:3001/categories
Content-Type: application/json
user: 2

{
  "type": "sobremesa"
}